Added support for running migrations before rehydrating state
adam-golab/redux-phoenix pull request #5
Opened 2019-07-15 17:23 UTC by adam-golab

Discussion about the desired feature can be found under the #4 issue.

TODO:
[ ] add documentation to the readme

2019-07-16 18:46 UTC, ThibautMarechal requested changes
First of all thanks ! It worked well for my use case.

Maybe it we should add a validation for the migrations objects.

The code may throw in the migrations (the classic Cannot read property of '...' ) 
Maybe a try / catch around the migrations can catch the error ?

2019-07-16 18:46 UTC, ThibautMarechal commented on src/reduxPhoenix.js
> +    const { persistedState, saveDate, migrations: appliedMigrations } = persistedValue || {};
You do not set "migrations" when saving into the storage

2019-07-16 18:48 UTC, adam-golab commented on src/reduxPhoenix.js
> +    const { persistedState, saveDate, migrations: appliedMigrations } = persistedValue || {};
It is saved. Please take a look on line 137

2019-07-16 18:49 UTC, ThibautMarechal commented on src/reduxPhoenix.js
> +    const { persistedState, saveDate, migrations: appliedMigrations } = persistedValue || {};
It was and old comment not submitted directly :)

2019-07-16 18:50 UTC, adam-golab commented on src/reduxPhoenix.js
> +    const { persistedState, saveDate, migrations: appliedMigrations } = persistedValue || {};
yeah, I forgot about it yesterday ;)

2019-07-16 18:59 UTC, adam-golab commented
@ThibautMarechal good idea. I added some null checks a moment ago. I don't think that wrapping it in a `try/catch` block is necessary here. 

But I added a few checks that only migrations with the `name` and `up/down` method will be applied

2019-07-16 19:14 UTC, ThibautMarechal approved these changes

2019-07-17 17:52 UTC, adam-golab commented
Published as a version: 1.3.0

2019-07-17 17:52 UTC, merged